# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treesite', '0002_auto_20170820_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
